version: '3.8'
services:
  app:
    build: .
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=myeventdb
      - MONGO_USER=mongo
      - MONGO_PASS=mongo
      - PYTHONPATH=/app
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
